- name: Iniciando MariaDB
  systemd:
    name: mariadb
    state: restarted
  when: ansible_os_family == "RedHat"

- name: Iniciando MySQL
  systemd:
    name: mysql
    state: restarted
  when: ansible_os_family == "Debian"
